print("    *        " *2)
print("   * *       " *2)
print("  *   *      " *2)
print(" *     *     " *2)
print("***   ***    " *2)
print("  *   *      " *2)
print("  *   *      " *2)
print("  *****      " *2)

print("         *\n\n","      *   *\n\n","    *       *\n\n","  *           *\n\n","* * *       * * *\n\n","    *       *\n\n","    *       *\n\n","    * * * * *\n\n")
